#define MICROSTEPS 1
#define STEPPER_STEPS_PER_ROTATION 200
#define STEPS_PER_ROTATION (STEPPER_STEPS_PER_ROTATION * MICROSTEPS)
#define MAX_RPM 10
#define MAX_US_PER_STEP (1000000 / STEPS_PER_ROTATION) / MAX_RPM

#define STEP_PIN 22
#define ENABLE_PIN 26
#define DIR_PIN 23
#define CW_PIN 14
#define CCW_PIN 12
#define FEED_RATE_PIN 36
#define ROTARY_PIN_A 18
#define ROTARY_PIN_B 19
#define TOGGLE_ENCODER_PIN 17
#define ENCODER_PULSES_PER_ROTATION 28
